# Generated by Django 5.1 on 2026-07-29 10:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_provider(apps, schema_editor):
    """Tag pre-existing rows, which all predate the provider field.

    The default is 'toss', so only the two non-Toss cases need correcting:
    PayPal payments were written with payment_type='PayPal', and manually
    entered payments (직접입력) carry a ManualTransaction.
    """
    PaymentHistory = apps.get_model('main', 'PaymentHistory')
    PaymentHistory.objects.filter(payment_type='PayPal').update(provider='paypal')
    PaymentHistory.objects.filter(manual_transaction__isnull=False).update(provider='manual')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_event_main_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='provider',
            field=models.CharField(choices=[('toss', 'Toss Payments'), ('paypal', 'PayPal'), ('nicepay', 'NicePay'), ('manual', 'Manual')], default='toss', max_length=20),
        ),
        migrations.CreateModel(
            name='NicePayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.IntegerField()),
                ('pay_method', models.CharField(default='CARD', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authenticated', 'Authenticated'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tid', models.CharField(blank=True, max_length=30)),
                ('result_code', models.CharField(blank=True, max_length=50)),
                ('result_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicepay_transactions', to='main.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicepay_transactions', to='main.event')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nicepay_transaction', to='main.paymenthistory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='main_nicepa_order_i_619144_idx'), models.Index(fields=['tid'], name='main_nicepa_tid_d30e09_idx')],
            },
        ),
        migrations.RunPython(backfill_provider, noop),
    ]
