# Generated by Django 5.1 on 2026-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_paymenthistory_provider_nicepaytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='business_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='representative_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
