# Generated by Django 5.1 on 2026-07-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_businesssettings_address_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this key is for, e.g. 'events MCP'", max_length=200)),
                ('prefix', models.CharField(db_index=True, editable=False, max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Set to disable this key without deleting it', null=True)),
                ('user', models.ForeignKey(help_text='Requests using this key act as this user', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
