# Generated by Django 5.1 on 2026-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domestic_provider', models.CharField(choices=[('toss', 'Toss Payments'), ('nicepay', 'NicePay'), ('none', 'Disabled')], default='toss', max_length=20)),
                ('international_provider', models.CharField(choices=[('paypal', 'PayPal'), ('none', 'Disabled')], default='paypal', max_length=20)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
