# Generated by Django 5.1 on 2026-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='organizer_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=20),
        ),
    ]
