# Generated by Django 5.1 on 2026-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='student_status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('pi_non_academic', 'PI / Non-academic')], default='pi_non_academic', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='graduate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee_graduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee_undergraduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='undergraduate_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
