# Generated by Django 5.1 on 2026-08-02 17:13

from django.db import migrations, models


def backfill_presentation_type(apps, schema_editor):
    """Map the old type/wants_short_talk pair onto the new field.

    Without this every existing abstract would keep the 'poster' default and
    silently lose the format its author asked for.
    """
    Abstract = apps.get_model('main', 'Abstract')
    Abstract.objects.filter(type='poster', wants_short_talk=True).update(
        presentation_type='short_talk_poster')
    Abstract.objects.filter(type='poster', wants_short_talk=False).update(
        presentation_type='poster')
    # 'speaker' meant an oral presentation; short talk is its closest equivalent.
    Abstract.objects.filter(type='speaker').update(presentation_type='short_talk')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_attendee_student_status_event_graduate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='presentation_type',
            field=models.CharField(choices=[('poster', 'Poster presentation only'), ('short_talk_poster', 'Short talk and poster presentation'), ('short_talk', 'Short talk only'), ('flash_talk_poster', 'Flash talk and poster presentation'), ('invited', 'Invited / Plenary talk')], default='poster', max_length=32),
        ),
        migrations.RunPython(backfill_presentation_type, noop),
    ]
