# Generated by Django 5.1 on 2026-08-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_abstract_presentation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='onsite_registration_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
