# Generated by Django 5.1 on 2026-08-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_event_onsite_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='onsite_registration_fee_graduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='onsite_registration_fee_undergraduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onsiteattendee',
            name='student_status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('pi_non_academic', 'PI / Non-academic')], default='pi_non_academic', max_length=20),
        ),
    ]
