# Generated by Django 5.1 on 2026-08-03 03:00

from django.db import migrations

CATEGORY_LINE = (
    "{% if event.has_tiered_fees %} - Registration Category: "
    "{{ attendee.get_student_status_display }}\n{% endif %}"
)
REGISTRATION_ANCHOR = "/register\n\n"

STALE_ABSTRACT_TYPE = (
    "{% if abstract.is_oral %}Oral Presentation{% else %}Poster Presentation{% endif %}"
)
ABSTRACT_TYPE = "{{ abstract.get_presentation_type_display }}"


def update_templates(apps, schema_editor):
    """Bring already-created event templates in line with the new defaults.

    Both edits are targeted and idempotent rather than a wholesale overwrite, so
    an organiser's customised wording is preserved: the category line is only
    inserted where the registration link still sits at the end of the details
    block and no category line exists yet, and the abstract type is only
    rewritten where the old broken conditional is still present.
    """
    EmailTemplate = apps.get_model('main', 'EmailTemplate')

    for template in EmailTemplate.objects.filter(body__contains=REGISTRATION_ANCHOR):
        if 'get_student_status_display' in template.body:
            continue
        template.body = template.body.replace(
            REGISTRATION_ANCHOR,
            "/register\n" + CATEGORY_LINE + "\n",
            1,
        )
        template.save(update_fields=['body'])

    # abstract.is_oral was never a field, so this always rendered
    # "Poster Presentation" - including for talks.
    for template in EmailTemplate.objects.filter(body__contains=STALE_ABSTRACT_TYPE):
        template.body = template.body.replace(STALE_ABSTRACT_TYPE, ABSTRACT_TYPE)
        template.save(update_fields=['body'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_event_onsite_registration_fee_graduate_and_more'),
    ]

    operations = [
        migrations.RunPython(update_templates, noop),
    ]
