# Generated by Django 5.1 on 2026-08-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_update_email_templates_for_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='student_status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate student'), ('graduate', 'Graduate student / Postdoc'), ('pi_non_academic', 'PI / Non-academic')], default='pi_non_academic', max_length=20),
        ),
        migrations.AlterField(
            model_name='onsiteattendee',
            name='student_status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate student'), ('graduate', 'Graduate student / Postdoc'), ('pi_non_academic', 'PI / Non-academic')], default='pi_non_academic', max_length=20),
        ),
    ]
