# Generated by Django 5.1 on 2026-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_email_templates_use_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='is_payment_exempt',
            field=models.BooleanField(default=True),
        ),
    ]
