# Generated by Django 5.1 on 2026-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_drop_speaker_waiver_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='fee_waived',
            field=models.BooleanField(default=False),
        ),
    ]
