# Generated by Django 5.1 on 2026-09-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_event_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='as_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='as_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='is_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='is_speaker',
            field=models.BooleanField(default=True),
        ),
    ]
