# Generated by Django 5.1 on 2026-10-09 08:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0086_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='toss_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='abstract',
            index=models.Index(fields=['file_path'], name='main_abstract_file_path_idx', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='main_user_email_upper_idx'),
        ),
    ]
