# Generated by Django 5.1 on 2026-10-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_lookup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
